version: '3'
services:
        database:
                container_name: leedor.mariadb
                environment:
                        - MYSQL_ALLOW_EMPTY_PASSWORD
                image: mariadb
                ports:
                        - "3306:3306"
                volumes:
                        - "./mysql:/var/lib/mysql"
                        - "/etc/localtime:/etc/localtime:ro"
        gotrue:
                container_name: leedor.gotrue
                build:
                        context: https://github.com/netlify/gotrue.git
                        dockerfile: Dockerfile
                depends_on:
                        - database
                environment:
                        - DATABASE_URL
                        - GOTRUE_API_HOST
                        - GOTRUE_DB_DRIVER
                        - GOTRUE_DISABLE_SIGNUP
                        - GOTRUE_JWT_AUD
                        - GOTRUE_JWT_EXP
                        - GOTRUE_JWT_SECRET
                        - GOTRUE_LOG_LEVEL
                        - GOTRUE_OPERATOR_TOKEN
                        - GOTRUE_SITE_URL
                        - PORT
                ports:
                        - "8081:8081"
                volumes:
                        - "/etc/localtime:/etc/localtime:ro"
